image:
  repository: ghcr.io/k8snetworkplumbingwg/dra-driver-ovsdpdk
  tag: ""           # defaults to .Chart.AppVersion
  pullPolicy: IfNotPresent

hugepages: {}
  # hugepages-1Gi: "4Gi"
  # hugepages-2Mi: "512Mi"

openshift:
  enabled: false    # set to true to create SecurityContextConstraints
