// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	pkgtypes "github.com/k8snetworkplumbingwg/dra-driver-ovsdpdk/pkg/types"
	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"
)

// MockCheckpoint is an autogenerated mock type for the Checkpoint type
type MockCheckpoint struct {
	mock.Mock
}

type MockCheckpoint_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckpoint) EXPECT() *MockCheckpoint_Expecter {
	return &MockCheckpoint_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockCheckpoint) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCheckpoint_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCheckpoint_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCheckpoint_Expecter) Close() *MockCheckpoint_Close_Call {
	return &MockCheckpoint_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCheckpoint_Close_Call) Run(run func()) *MockCheckpoint_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckpoint_Close_Call) Return(_a0 error) *MockCheckpoint_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCheckpoint_Close_Call) RunAndReturn(run func() error) *MockCheckpoint_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: claimUID
func (_m *MockCheckpoint) Delete(claimUID types.UID) error {
	ret := _m.Called(claimUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UID) error); ok {
		r0 = rf(claimUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCheckpoint_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCheckpoint_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - claimUID types.UID
func (_e *MockCheckpoint_Expecter) Delete(claimUID interface{}) *MockCheckpoint_Delete_Call {
	return &MockCheckpoint_Delete_Call{Call: _e.mock.On("Delete", claimUID)}
}

func (_c *MockCheckpoint_Delete_Call) Run(run func(claimUID types.UID)) *MockCheckpoint_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UID))
	})
	return _c
}

func (_c *MockCheckpoint_Delete_Call) Return(_a0 error) *MockCheckpoint_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCheckpoint_Delete_Call) RunAndReturn(run func(types.UID) error) *MockCheckpoint_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with no fields
func (_m *MockCheckpoint) Load() (map[types.UID][]*pkgtypes.PreparedDevice, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 map[types.UID][]*pkgtypes.PreparedDevice
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[types.UID][]*pkgtypes.PreparedDevice, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[types.UID][]*pkgtypes.PreparedDevice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.UID][]*pkgtypes.PreparedDevice)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCheckpoint_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockCheckpoint_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockCheckpoint_Expecter) Load() *MockCheckpoint_Load_Call {
	return &MockCheckpoint_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockCheckpoint_Load_Call) Run(run func()) *MockCheckpoint_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckpoint_Load_Call) Return(_a0 map[types.UID][]*pkgtypes.PreparedDevice, _a1 error) *MockCheckpoint_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCheckpoint_Load_Call) RunAndReturn(run func() (map[types.UID][]*pkgtypes.PreparedDevice, error)) *MockCheckpoint_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: claimUID, devices
func (_m *MockCheckpoint) Store(claimUID types.UID, devices []*pkgtypes.PreparedDevice) error {
	ret := _m.Called(claimUID, devices)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UID, []*pkgtypes.PreparedDevice) error); ok {
		r0 = rf(claimUID, devices)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCheckpoint_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockCheckpoint_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - claimUID types.UID
//   - devices []*pkgtypes.PreparedDevice
func (_e *MockCheckpoint_Expecter) Store(claimUID interface{}, devices interface{}) *MockCheckpoint_Store_Call {
	return &MockCheckpoint_Store_Call{Call: _e.mock.On("Store", claimUID, devices)}
}

func (_c *MockCheckpoint_Store_Call) Run(run func(claimUID types.UID, devices []*pkgtypes.PreparedDevice)) *MockCheckpoint_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UID), args[1].([]*pkgtypes.PreparedDevice))
	})
	return _c
}

func (_c *MockCheckpoint_Store_Call) Return(_a0 error) *MockCheckpoint_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCheckpoint_Store_Call) RunAndReturn(run func(types.UID, []*pkgtypes.PreparedDevice) error) *MockCheckpoint_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckpoint creates a new instance of MockCheckpoint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckpoint(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckpoint {
	mock := &MockCheckpoint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
