// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	pkgtypes "github.com/k8snetworkplumbingwg/dra-driver-ovsdpdk/pkg/types"
	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"
)

// MockPodManagerIface is an autogenerated mock type for the PodManagerIface type
type MockPodManagerIface struct {
	mock.Mock
}

type MockPodManagerIface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPodManagerIface) EXPECT() *MockPodManagerIface_Expecter {
	return &MockPodManagerIface_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: claimUID
func (_m *MockPodManagerIface) Delete(claimUID types.UID) error {
	ret := _m.Called(claimUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UID) error); ok {
		r0 = rf(claimUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPodManagerIface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPodManagerIface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - claimUID types.UID
func (_e *MockPodManagerIface_Expecter) Delete(claimUID interface{}) *MockPodManagerIface_Delete_Call {
	return &MockPodManagerIface_Delete_Call{Call: _e.mock.On("Delete", claimUID)}
}

func (_c *MockPodManagerIface_Delete_Call) Run(run func(claimUID types.UID)) *MockPodManagerIface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UID))
	})
	return _c
}

func (_c *MockPodManagerIface_Delete_Call) Return(_a0 error) *MockPodManagerIface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPodManagerIface_Delete_Call) RunAndReturn(run func(types.UID) error) *MockPodManagerIface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: claimUID
func (_m *MockPodManagerIface) Get(claimUID types.UID) ([]*pkgtypes.PreparedDevice, error) {
	ret := _m.Called(claimUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*pkgtypes.PreparedDevice
	var r1 error
	if rf, ok := ret.Get(0).(func(types.UID) ([]*pkgtypes.PreparedDevice, error)); ok {
		return rf(claimUID)
	}
	if rf, ok := ret.Get(0).(func(types.UID) []*pkgtypes.PreparedDevice); ok {
		r0 = rf(claimUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pkgtypes.PreparedDevice)
		}
	}

	if rf, ok := ret.Get(1).(func(types.UID) error); ok {
		r1 = rf(claimUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPodManagerIface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPodManagerIface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - claimUID types.UID
func (_e *MockPodManagerIface_Expecter) Get(claimUID interface{}) *MockPodManagerIface_Get_Call {
	return &MockPodManagerIface_Get_Call{Call: _e.mock.On("Get", claimUID)}
}

func (_c *MockPodManagerIface_Get_Call) Run(run func(claimUID types.UID)) *MockPodManagerIface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UID))
	})
	return _c
}

func (_c *MockPodManagerIface_Get_Call) Return(_a0 []*pkgtypes.PreparedDevice, _a1 error) *MockPodManagerIface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPodManagerIface_Get_Call) RunAndReturn(run func(types.UID) ([]*pkgtypes.PreparedDevice, error)) *MockPodManagerIface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: claimUID, sc
func (_m *MockPodManagerIface) Set(claimUID types.UID, sc []*pkgtypes.PreparedDevice) error {
	ret := _m.Called(claimUID, sc)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UID, []*pkgtypes.PreparedDevice) error); ok {
		r0 = rf(claimUID, sc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPodManagerIface_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockPodManagerIface_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - claimUID types.UID
//   - sc []*pkgtypes.PreparedDevice
func (_e *MockPodManagerIface_Expecter) Set(claimUID interface{}, sc interface{}) *MockPodManagerIface_Set_Call {
	return &MockPodManagerIface_Set_Call{Call: _e.mock.On("Set", claimUID, sc)}
}

func (_c *MockPodManagerIface_Set_Call) Run(run func(claimUID types.UID, sc []*pkgtypes.PreparedDevice)) *MockPodManagerIface_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UID), args[1].([]*pkgtypes.PreparedDevice))
	})
	return _c
}

func (_c *MockPodManagerIface_Set_Call) Return(_a0 error) *MockPodManagerIface_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPodManagerIface_Set_Call) RunAndReturn(run func(types.UID, []*pkgtypes.PreparedDevice) error) *MockPodManagerIface_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPodManagerIface creates a new instance of MockPodManagerIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPodManagerIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPodManagerIface {
	mock := &MockPodManagerIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
